.TH macf 1 "August 2025" "1.1" "MAC Address Formatter"
.SH NAME
macf \- A program to format MAC addresses into various styles.

.SH SYNOPSIS
.B macf
[\fIMAC_ADDRESS\fR  \fIMAC_ADDRESS\fR] \fIFORMAT\fR [\fB-f\fR \fIFILE\fR] [\fB-v\fR]

.SH DESCRIPTION
.B macf
is a utility that converts MAC addresses into various formats. It can process a single MAC address provided as an argument or multiple MAC addresses from a file. Invalid MAC addresses can be logged to a separate error file.

The available formats include:
.IP
- Cisco format: \fB0000.0000.0000\fR
.IP
- Dash-separated format: \fB00-00-00-00-00-00\fR
.IP
- Colon-separated format: \fB00:00:00:00:00:00\fR
.IP
- Raw format (no separators): \fB000000000000\fR

By default, the program outputs results to standard output unless the \fB-o\fR flag is used to specify an output file.

.SH OPTIONS
.TP
\fIMAC_ADDRESS\fR
Specifies a single MAC address to process. This can be provided directly as an argument.

.TP
\fB-f\fR, \fB--file\fR \fIFILE\fR
Specifies a file containing multiple MAC addresses to process. Each MAC address should be on a separate line. The program will process all MAC addresses in the file.

.TP
\fB-v\fR
Enables verbose output. Displays conversion details and errors in the terminal.

.TP
\fIFORMAT\fR
Specifies the format to convert MAC addresses into. Supported formats are:
.IP
- \fBcisco\fR: \fB0000.0000.0000\fR
.IP
- \fBdash\fR: \fB00-00-00-00-00-00\fR
.IP
- \fBcolon\fR: \fB00:00:00:00:00:00\fR
.IP
- \fBraw\fR: \fB000000000000\fR

.SH EXAMPLES
.TP
Convert a single MAC address to Cisco format:
.B macf 00-11-22-33-44-55 cisco
.TP
Convert MAC addresses from a file to dash format:
.B macf -f macs.txt dash
.TP
Enable verbose mode while processing a single MAC address:
.B macf 00-11-22-33-44-55 colon -v

.SH AUTHOR
Written by Kenneth Parnell - taylor@chronobyte.net.

.SH BUGS
No known bugs. Please report issues to taylor@chronobyte.net.
